In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("./cleaned Datasets/MetaData.csv")
df2 = pd.read_csv("./cleaned Datasets/ProductInfo.csv")

In [3]:
df1.head(2)

,product Id,name,sub_category,main_category,image,link,discount_price,actual_price,ratings,no_of_ratings
0,P1,Gadson RO Solenoid Valve 24 VDC for Kent/AQUAG...,All Appliances,appliances,https://m.media-amazon.com/images/I/21h-aU43wL...,https://www.amazon.in/Gadson-Solenoid-Valve-Aq...,150.0,300.0,3.0,292
1,P2,Van Heusen Sport Men's Slim Shirt (VSSFWSLP299...,Men's Fashion,stores,https://m.media-amazon.com/images/I/91RVshFBEM...,https://www.amazon.in/Van-Heusen-Sport-Shirt-V...,619.0,2299.0,4.0,5

In [4]:
df2.head(2)

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price,product Id,discount percentage,Rating Bucket,Popularity Score,Value Score,cleaned_name,cleaned_sub_category,tags
0,Gadson RO Solenoid Valve 24 VDC for Kent/AQUAG...,appliances,All Appliances,3.0,292,150.0,300.0,P1,50.00000,Average,17.040518,0.113603,gadson ro solenoid valve 24 vdc for kentaquaga...,Appliances,appliances All Appliances Gadson RO Solenoid V...
1,Van Heusen Sport Men's Slim Shirt (VSSFWSLP299...,stores,Men's Fashion,4.0,5,619.0,2299.0,P2,73.07525,Good,7.167038,0.011578,van heusen sport men's slim shirt (vssfwslp299...,Men's Fashion,stores Men's Fashion Van Heusen Sport Men's Sl...

In [5]:
df1.columns

Index(['product Id', 'name', 'sub_category', 'main_category', 'image', 'link',
       'discount_price', 'actual_price', 'ratings', 'no_of_ratings'],
      dtype='object')

In [6]:
import requests

def check_image(url):
    try:
        response = requests.get(url, timeout=5)

        return response.status_code == 200

    except:
        return False

In [9]:
df1['sub_category'].value_counts()

sub_category
Ethnic Wear                   16183
Men's Fashion                 15267
All Appliances                 8503
Home Entertainment Systems     8503
All Electronics                8076
Headphones                     7842
Car Accessories                1381
Home Décor                     1205
Name: count, dtype: int64